### ISSUE TITLE
HTML export include image thumb instead of URL

### ISSUE THREAD

**Issue by sebastian-works** [doefom/statamic-export#4]
Hello, 
When exporting HTML would it be possible to to export an image thumbnail instead of printing the URL?

Thanks!

**Comment by doefom** [comment]
Hi @albertvisuals, thanks for reaching out! I think this would be doable. For exporting to HTML I'm using the export functionality of Laravel Excel (https://docs.laravel-excel.com/3.1/exports/export-formats.html#html). I guess one would need to hook into `Excel::download` to add the images when the export format is HTML. Since exporting thumbnails is not the default I'd prefer to leave it as is.

However, if you got some spare time and want to develop this anyway, feel free to open a PR! I'd be happy to review it!
